# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "store_base_sti_class"
  s.version = "0.1.1"

  s.authors = ["Andrew Mutz"]
  s.date = "2013-11-28"
  s.description = "\n    ActiveRecord has always stored the base class in polymorphic _type columns when using STI. This can have non-trivial\n    performance implications in certain cases. This gem adds 'store_base_sti_class' configuration options which controls\n    whether ActiveRecord will store the base class or the actual class. Default to true for backwards compatibility.\n  "
  s.email = "andrew.mutz@appfolio.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")

  s.homepage = "http://github.com/appfolio/store_base_sti_class"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Modifies ActiveRecord 3.0.5 - 4.1.4 with the ability to store the actual class (instead of the base class) in polymorhic _type columns when using STI"

  s.add_dependency 'activerecord'
  if s.respond_to? :add_develoment_dependency
    s.add_development_dependency 'sqlite3'
    s.add_development_dependency 'appraisal'
  else 
    s.add_dependency 'sqlite3'
    s.add_dependency 'appraisal'
  end
  s.add_dependency 'bundler'
end

